import { requireUser, getProfile } from "@/lib/auth";
import { listModels } from "./actions";
import { ModelPicker } from "./model-picker";

export default async function SettingsPage() {
  await requireUser();
  const [profile, { models, live }] = await Promise.all([getProfile(), listModels()]);

  const envDefault = process.env.AI_MODEL || "gpt-4o";
  const aiConfigured = Boolean(process.env.AI_API_KEY || process.env.OPENAI_API_KEY);

  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <div>
        <h1 className="text-page font-semibold text-paper-900">Settings</h1>
        <p className="mt-1 text-body break-words text-paper-600">
          {profile?.email}
          {profile?.role ? ` · ${profile.role}` : ""}
        </p>
      </div>

      {!aiConfigured ? (
        <div className="rounded-surface border border-status-risk-200 bg-status-risk-50 px-4 py-3 text-body text-status-risk-800">
          No AI provider key is set in the environment yet, so minutes are generated by the built-in
          rule-based engine. Add <code>AI_API_KEY</code> (and <code>AI_BASE_URL</code> for OpenRouter)
          in Vercel to enable model selection below.
        </div>
      ) : null}

      <ModelPicker
        models={models}
        live={live}
        current={profile?.ai_model ?? null}
        envDefault={envDefault}
      />
    </div>
  );
}
